---
title: "`SurveyOptions`"
subtitle: "Change Survey's behaviour"
description: "A class of options that can be applied to a [Survey](/ref/structure/Survey.qmd) object. Main possibilities include setting a language and redirect URL. All currently available options can be found below."
aliases: 
  - ../SurveyOptions.html
categories:
  - "`velesresearch`"
  - "`velesresearch.options`"
---
# Modules

`velesresearch`

`velesresearch.options`

# Usage

``` {python}
PageOptions(
    language="en",
    timer_position="none",
    timer_mode="",
    url_on_complete=None,
    allow_previous=True,
    clear_invivsible_values="none",
)
```


# Arguments

::: arg_name
language
:::
::: arg_desc
`str`; language code. List of available languages available [here](https://github.com/surveyjs/survey-library/tree/master/src/localization).
:::

::: arg_name
timer_position
:::
::: arg_desc
`str`; position of the timer. Possible values: `top`, `bottom`, `none`. If there's no time limit, the timer will count up from 0.
:::

::: arg_name
timer_mode
:::
::: arg_desc
`str`; mode of the timer. Possible values: `page`, `survey`, `all`. Controls what times should be shown. `page` shows time spent on the current page, `survey` shows time spent on the whole survey, `all` shows both.
:::

::: arg_name
url_on_complete
:::
::: arg_desc
`str`; webpage to which the respondent should be redirected after completing the survey.
:::

::: arg_name
allow_previous
:::
::: arg_desc
`bool`; whether the respondent should be able to go back to previous pages.
:::

::: arg_name
clear_invivsible_values
:::
::: arg_desc
`str` or `bool`; whether to clear invisible values. Possible values: `none` (or `False`), `onHidden`, `onHiddenContainer`, `onComplete` (or `True`). If `none`, no values will be cleared. If `onHidden`, values will be cleared when the question is hidden. `onHiddenContainer` clears value when questions' page or panel gets hidden. If `onComplete`, values of hidden questions will be cleared when the survey is completed.
:::

# Value

An object of class `SurveyOptions`.

# Examples

``` {python}
# | eval: true
# | output: false

from velesresearch import question, page, survey, SurveyOptions

drinks = "Tea, Coffee, Water".split(", ")
answers = "My favourite, I like it, Neutral, I don't like it, I despise it".split(", ")

q = question("drinks", drinks, answers)
p = page("drinks", q, title="Favourite drinks")
survey(
    "drink_survey",
    p,
    options=SurveyOptions(url_on_complete="https://en.wikipedia.org/wiki/Tea"),
    create=False,  # for example sake, you probably want to create
)
```