---
title: "Brief COPE (Mini-COPE)"
subtitle: "`mini_cope()`"
description: "The questionnaire is used to assess ways of coping with stress. It is intended mainly for research purposes, but it can also be used in practice, in screening and preventive studies, and in assessing the effectiveness of therapeutic interventions. The Brief COPE omits two scales of the full COPE, reduces others to two items per scale, and adds one scale."
categories: ["Cognitive and Behavioral Assessments"]
---

## Module
`velesresearch.questionnaires.mini_cope`

## Import
``` python
from velesresearch.questionnaires.mini_cope import mini_cope
```

## Original
<div class="csl-bib-body" style="line-height: 2; margin-left: 2em; text-indent:-2em;">
<div class="csl-entry">Carver, C. S. (1997). You want to measure coping but your protocol’ too long: Consider the brief cope. <i>International Journal of Behavioral Medicine</i>, <i>4</i>(1), 92–100. <https://doi.org/10.1207/s15327558ijbm0401_6></div>
</div>

## Score calculation
An average.

## Reverse items
None.

## Subscales
1. Active Coping: 1, 2
2. Planning: 3, 4
3. Positive Refraining : 5, 6
4. Acceptance: 7, 8
5. Humor: 9, 10
6. Religion: 11, 12
7. Using Emotional Support: 13, 14
8. Using Instrumental Support: 15, 16
9. Self-Distraction: 17, 18
10. Denial: 19, 20
11. Venting: 21, 22
12. Substance Use: 23, 24
13. Behavioral Disengagement: 25, 26
14. Self-Blame: 27, 28

## Reliability
1. Active Coping: α = .68
2. Planning: α = .73
3. Positive Refraining : α = .64
4. Acceptance: α = .57
5. Humor: α = .73
6. Religion: α = .82
7. Using Emotional Support: α = .71
8. Using Instrumental Support: α = .64
9. Self-Distraction: α = .71
10. Denial: α = .54
11. Venting: α = .5
12. Substance Use: α = .9
13. Behavioral Disengagement: α = .65
14. Self-Blame: α = .69

## Implemented by
Julia Jankowska (University of Wrocław)

## Args
`name` : *str*<br>
Base name for pages and questions. Defaults to "mini_cope".

`instruction` : *str*<br>
Instruction for the questionnaire. None means that the default instruction will be used.

`questionOptions` : *dict | None*<br>
Additional options for questions as a dictionary. Defaults to None.

`pageOptions` : *dict | None*<br>
Additional options for pages as a dictionary. Defaults to None.


## Returns
`PageModel`<br>
PageModel with the Mini-COPE questionnaire. Use the `*` operator to unpack it to questions.
