---
title: "Ten Item Personality Inventory (TIPI)"
subtitle: "`tipi()`"
description: "Ten item adaptation of Big Five. Measures five personality traits: Extraversion, Agreeableness, Conscientiousness, Emotional Stability and Openness to Experience."
categories: [personality]
---

## Module
`veleslibrary.questionnaires.pl.tipi`

## Import
``` python
from veleslibrary.questionnaires.pl.tipi import tipi
```

## Original
<div class="csl-bib-body" style="line-height: 2; margin-left: 2em; text-indent:-2em;">
<div class="csl-entry">Gosling, S. D., Rentfrow, P. J., &amp; Swann, W. B. (2003). A very brief measure of the Big-Five personality domains. <i>Journal of Research in Personality</i>, <i>37</i>(6), 504–528. <https://doi.org/10.1016/S0092-6566(03)00046-1></div>
</div>

## Adaptation
<div class="csl-bib-body" style="line-height: 2; margin-left: 2em; text-indent:-2em;">
<div class="csl-entry">Sorokowska, A., Słowińska, A., Zbieg, A., &amp; Sorokowski, P. (2014). <i>Polska adaptacja testu Ten Item Personality Inventory (Tipi) – TIPI-PL – wersja standardowa i internetowa</i>. Wrocław: WrocLab.</div>
</div>

## Score calculation
A simple sum.

## Reverse items
2, 4, 6, 8, 10

## Subscales
1. Extraversion: 1, 6
2. Agreeableness: 2, 7
3. Conscientiousness: 3, 8
4. Emotional Stability: 4, 9
5. Openness to Experience: 5, 10

## Reliability

### Paper and pencil
1. Extraversion: α = .68
2. Agreeableness: α = .58
3. Conscientiousness: α = .75
4. Emotional Stability: α = .72
5. Openness to Experience: α = .44

### Google Forms
1. Extraversion: α = .74
2. Agreeableness: α = .54
3. Conscientiousness: α = .80
4. Emotional Stability: α = .83
5. Openness to Experience: α = .45

### Online application
1. Extraversion: α = .70
2. Agreeableness: α = .50
3. Conscientiousness: α = .76
4. Emotional Stability: α = .65
5. Openness to Experience: α = .47

## Implemented by
Jędrusiak, Jakub (University of Wrocław)

## Args
`name` : *str*<br>
Base name for pages and questions. Defaults to "TIPI".

`instruction` : *str*<br>
Instruction for the questionnaire. Defaults to "Poniżej przedstawiona jest lista cech, które <u>są lub nie są</u> Twoimi charakterystykami. Zaznacz przy poszczególnych stwierdzeniach, do jakiego stopnia <u>zgadzasz się lub nie zgadzasz</u> z każdym z nich. Oceń stopień, w jakim każde z pytań odnosi się do Ciebie.".

`questionOptions` : *dict | None*<br>
Additional options for questions as a dictionary. Defaults to None.

`pageOptions` : *dict | None*<br>
Additional options for pages as a dictionary. Defaults to None.

## Returns
`PageModel`<br>
PageModel with the TIPI questionnaire.