---
title: "Question types"
subtitle: "Wrappers and available types of questions"
description: "Veles includes a series of different question types. Each of them can be passed as the `question_type` argument in [`question()`](./question.qmd) (or directly in [`Question()`](/ref/structure/Question.qmd). Every question type also has a wrapper that allows to create a [Question](/ref/structure/Question.qmd) object quicker. For example you can create a radio question with `question(question_type=\"radio\")` or with `radio()`."
aliases: 
  - ../questiontypes.html
categories:
  - "`velesresearch`"
  - "`velesresearch.questiontypes`"
---

| Question type    | Description                                   |
|------------------|-----------------------------------------------|
| `checkbox`       | multiple choice question                      |
| `dropdown`       | single choice question with a dropdown list   |
| `dropdown_multi` | multiple choice question with a dropdown list |
| `radio`          | single choice question                        |
| `ranking`        | question to rank given items                  |
| `text`           | short text field                              |
| `text_long`      | long text box                                 |
| `yes_no`         | a yes/no question                             |

# `checkbox`

Multiple choice question. Just like `radio` but allows to pick multiple answers.

::: light-mode
```{=html}
<iframe src="https://codesandbox.io/embed/veles-checkbox-zjmzhc?fontsize=14&hidenavigation=1&theme=light&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Veles – checkbox"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```
:::
::: dark-mode
```{=html}
<iframe src="https://codesandbox.io/embed/veles-checkbox-zjmzhc?fontsize=14&hidenavigation=1&theme=dark&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Veles – checkbox"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
   ```
:::

# `dropdown`

Single choice question. Just like `radio` but with a dropdown list.

::: light-mode
``` {=html}
<iframe src="https://codesandbox.io/embed/kind-wave-yg86kq?fontsize=14&hidenavigation=1&theme=light&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Veles – dropdown"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```
:::
::: dark-mode
``` {=html}
<iframe src="https://codesandbox.io/embed/kind-wave-yg86kq?fontsize=14&hidenavigation=1&theme=dark&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Veles – dropdown"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```
:::

# `dropdown_multi`

Multiple choice question. Just like `checkbox` but with a dropdown list.

::: light-mode
``` {=html}
<iframe src="https://codesandbox.io/embed/veles-dropdown-multi-tw93f4?fontsize=14&hidenavigation=1&theme=light&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Veles – dropdown_multi"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```
:::
::: dark-mode
``` {=html}
<iframe src="https://codesandbox.io/embed/veles-dropdown-multi-tw93f4?fontsize=14&hidenavigation=1&theme=dark&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Veles – dropdown_multi"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```
:::

# `radio`

Single choice question. Can have "None" and "Other" options (available through [options](/ref/options/QuestionOptions.qmd)).

::: light-mode
```{=html}
<iframe src="https://codesandbox.io/embed/veles-radio-stm95y?fontsize=14&hidenavigation=1&theme=light&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Veles – radio"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```
:::
::: dark-mode
```{=html}
<iframe src="https://codesandbox.io/embed/veles-radio-stm95y?fontsize=14&hidenavigation=1&theme=dark&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Veles – radio"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```
:::

# `ranking`

Question to rank given items e.g. from best to worst.

::: light-mode
``` {=html}
<iframe src="https://codesandbox.io/embed/veles-ranking-x546t9?fontsize=14&hidenavigation=1&theme=light&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Veles – ranking"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```
:::
::: dark-mode
``` {=html}
<iframe src="https://codesandbox.io/embed/veles-ranking-x546t9?fontsize=14&hidenavigation=1&theme=dark&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Veles – ranking"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```
:::

# `text`

Short text field. For longer text use `text_long`.

::: light-mode
``` {=html}
<iframe src="https://codesandbox.io/embed/veles-text-qttwmt?fontsize=14&hidenavigation=1&theme=light&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Veles – text"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```
:::
::: dark-mode
``` {=html}
<iframe src="https://codesandbox.io/embed/veles-text-qttwmt?fontsize=14&hidenavigation=1&theme=dark&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Veles – text"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```
:::

# `text_long`

Long text box. For shorter text use `text`.

::: light-mode
``` {=html}
<iframe src="https://codesandbox.io/embed/veles-text-long-2kpj68?fontsize=14&hidenavigation=1&theme=light&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Veles – text_long"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```
:::
::: dark-mode
``` {=html}
<iframe src="https://codesandbox.io/embed/veles-text-long-2kpj68?fontsize=14&hidenavigation=1&theme=dark&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Veles – text_long"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```
:::

# `yes_no`

A yes/no question with a simple switch.

::: light-mode
``` {=html}
<iframe src="https://codesandbox.io/embed/veles-yes-no-m4y9jy?fontsize=14&hidenavigation=1&theme=light&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Veles – yes_no"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```
:::
::: dark-mode
``` {=html}
<iframe src="https://codesandbox.io/embed/veles-yes-no-m4y9jy?fontsize=14&hidenavigation=1&theme=dark&view=preview"
     style="width:100%; height:500px; border:0; border-radius: 4px; overflow:hidden;"
     title="Veles – yes_no"
     allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
     sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
   ></iframe>
```
:::