---
title: "`questionnaire`"
subtitle: "Convert a questionnaire to a list of questions"
description: "Often we have a whole questionnaire in our research survey. To make it easier, Veles allows to bulk create Question objects for every item with `questionnaire()`."
aliases: 
  - ../questionnaire.html
categories:
  - "`velesresearch`"
  - "`velesresearch.tools`"
---
# Modules

`velesresearch`

`velesresearch.tools`

# Usage

``` {python}
questionnaire(
    label, items, answers, question_type="radio", description=None, options=None
)
```

# Arguments

::: arg_name
label
:::
::: arg_desc
`str`; base for labelling the questionnaire. Usually the questionnaire's abbreviation (e.g. MMPI). The output questions will be labelled `label_number` e.g. `MMPI_1`, `MMPI_2`, ..., `MMPI_567`.
:::

::: arg_name
items
:::
::: arg_desc
`list[str]`; list of questions. Can be easily created with `.split()` method (see [Examples](#sec-examples)).
:::

::: arg_name
answers
:::
::: arg_desc
`list[str]` or `str`; scale for all questions. Every question must have the same scale.
:::

::: arg_name
question_type
:::
::: arg_desc
`str`; question type, `"radio"` by default. For list of available question types see [Question Types](./question_types.qmd).
:::

::: arg_name
description
:::
::: arg_desc
`str`; description for all questions. Looks like a subtitle.
:::

::: arg_name
options
:::
::: arg_desc
`QuestionOptions`; a `QuestionOptions` controlling options for all questions. For available options see [`QuestionOptions()`](../options/QuestionOptions.qmd).
:::

# Value

A list of `Question` objects.

# See also

- [`question()`](./question.qmd) for creating single `Question` objects.

- [Question types](./question_types.qmd) for available question types.

- [`QuestionOptions()`](../options/QuestionOptions) for available question modifications.

- [`page()`](./page.qmd) for composing questions into pages.

# Examples {#sec-examples}

``` {python}
# | eval: true
# | output: false
from velesresearch import questionnaire, QuestionOptions

# split items by new lines
# triple-quotation for multi-line strings
RSSI_items = """I feel that I am a person of worth, at least on an equal plane with others.
I feel that I have a number of good qualities.
All in all, I am inclined to feel that I am a failure.
I am able to do things as well as most other people.
I feel I do not have much to be proud of.
I take a positive attitude toward myself.
On the whole, I am satisfied with myself.
I wish I could have more respect for myself.
I certainly feel useless at times.
At times I think I am no good at all.""".split("\n")

# split scale by semicolons and spaces
scale = "Strongly Agree; Agree; Disagree; Strongly Disagree".split("; ")

# make it a list of questions
RRSI = questionnaire("RSSI", RSSI_items, scale, options=QuestionOptions(required=True))
```