---
title: "`survey`"
subtitle: "Create `Survey` object and build website"
description: "A handy wrapper around [`Survey()`](../structure/Survey). Joins `Page` objects into a survey and generates all survey website files."
aliases: 
  - ../survey.html
categories:
  - "`velesresearch`"
  - "`velesresearch.tools`"
---
# Modules

`velesresearch`

`velesresearch.tools`

# Usage

``` {python}
survey(label, *pages, title=None, description=None, options=None, create=True)
```


# Arguments

::: arg_name
label
:::
::: arg_desc
`str`; internal label of the survey. Will become webpage title.
:::

::: arg_name
\*pages
:::
::: arg_desc
`list[Page]` or `Page`; list of `Page` objects or a single `Page` object that will create a survey.
:::

::: arg_name
title
:::
::: arg_desc
`str`; title of the survey. Will be visible in the header.
:::

::: arg_name
description
:::
::: arg_desc
`str`; text just under survey header.
:::

::: arg_name
options
:::
::: arg_desc
`SurveyOptions`; options object created with [`SurveyOptions()`](../options/SurveyOptions.qmd), changes behaviour of the survey.
:::

::: arg_name
create
:::
::: arg_desc
`bool` or `str` or `Path`; controls whether survey is created and then built. Can be done later with `create()` method. Can be set to `True` but can also be a path to a folder where the survey files will be created. If `False`, no additional files are created.
:::

# Value

A `Survey` object. If `create=True` or path, a set of other files and folders are created. Folders `src` and `public` contain webpage raw React code. Folder `build` contains raw, ready to be deployed webpage. `package.json`, `package-lock.json` and `node-libraries` are JavaScript dependencies. When the survey is created for the first time, these dependencies are downloaded from the web.

# See also

[`SurveyOptions()`](../options/SurveyOptions) for available survey modifications.

# Examples

``` {python}
# | eval: true
# | output: false
from velesresearch import question, page, survey

gender = question(
    "gender",
    "What is your gender?",
    "Woman",
    "Man",
    "Other/I don't want to answer",
)

metric = page("metric", gender)

survey("Just metric", metric, create=False)
```